CREATE DATABASE SpringCT;

USE SpringCT;

CREATE TABLE STUDENT (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name VARCHAR(1000) NOT  NULL,
	Phone VARCHAR(1000) NOT NULL,
	Email VARCHAR(1000) NOT NULL
);

CREATE TABLE COURSES (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name VARCHAR(1000) NOT  NULL
);

CREATE TABLE COURSES_ENROLLED (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	StudentId INT,
	CourseId INT,
	FOREIGN KEY (StudentId) REFERENCES STUDENT(Id),
	FOREIGN KEY (CourseId) REFERENCES COURSES(Id),
);

INSERT INTO COURSES (Name) VALUES ('History'), ('Physics'), ('Mathematics'), ('Accounts');

SELECT * FROM STUDENT (nolock);
SELECT * FROM COURSES (nolock);
SELECT * FROM COURSES_ENROLLED (nolock);
